/**
 * companion/talk-flash.companionconfig is generated by
 * tools/talk-flash-config.mjs. This fails if the committed file and the
 * generator drift, and checks the parts of it the talk flash depends on.
 */
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
/* eslint-disable n/no-missing-import -- the rule maps .mjs to .mts when a .ts file imports it */
// @ts-expect-error — a plain .mjs tool, no type declarations
import { buildTalkFlashConfig, CONNECTION_ID, FILE_PAGE, OUTPUT } from '../../tools/talk-flash-config.mjs'
/* eslint-enable n/no-missing-import */
import { TALK_FLASH_EXIT, TALK_FLASH_FEEDBACK, TALK_FLASH_VARIABLES } from './talkflash-defs.js'
import { TALK_FLASH_DEFAULT_PAGE } from './talkflash.js'

type Json = Record<string, any>
const built = buildTalkFlashConfig() as Json

describe('the importable TALK page', () => {
	it('is exactly what the generator writes', () => {
		expect(JSON.parse(readFileSync(OUTPUT, 'utf8'))).toEqual(built)
	})

	it('holds one page, as page 1 where the import picker starts', () => {
		expect(Object.keys(built.pages)).toEqual([String(FILE_PAGE)])
		expect(FILE_PAGE).toBe(1)
	})

	it('ships the connection with no TALK page set, so nothing switches until the user sets it', () => {
		expect(built.instances[CONNECTION_ID].config.talkFlashPage).toBe(TALK_FLASH_DEFAULT_PAGE)
		expect(TALK_FLASH_DEFAULT_PAGE).toBe(0)
		expect(built.triggers.talkFlashStart.condition[0].options.expression.value).toContain('$(tlt:talk_page) > 0')
	})

	it('writes internal entities the way Companion exports them', () => {
		const exit = built.pages[FILE_PAGE].controls[0][0]
		const entities = [
			exit.steps[0].action_sets.down[0],
			...Object.values(built.triggers as Json).flatMap((t) => [...t.actions, ...t.condition]),
		]
		for (const e of entities) {
			expect(e.connectionId).toBe('internal')
			expect(e.children).toEqual({})
			expect(e).not.toHaveProperty('upgradeIndex')
		}
	})

	it('EXIT top-left, 31 TALK keys, all flashing from the connection', () => {
		const controls = built.pages[FILE_PAGE].controls as Json
		const keys = Object.values(controls).flatMap((row) => Object.values(row as Json)) as Json[]
		expect(keys).toHaveLength(32)
		const exit = controls[0][0]
		expect(exit.steps[0].action_sets.down.map((a: Json) => [a.connectionId, a.definitionId])).toEqual([
			['internal', 'set_page'],
			[CONNECTION_ID, TALK_FLASH_EXIT],
		])
		expect(exit.steps[0].action_sets.down[0].options).toEqual({
			surfaceId: { value: 'self', isExpression: false },
			page: { value: 'back', isExpression: false },
		})
		const talk = keys.filter((k) => k !== exit)
		expect(talk.every((k) => k.feedbacks[0].definitionId === TALK_FLASH_FEEDBACK)).toBe(true)
		expect(talk.every((k) => k.feedbacks[0].connectionId === CONNECTION_ID)).toBe(true)
	})

	it('the triggers read only variables this module defines', () => {
		const text = JSON.stringify(built.triggers)
		const used = [...text.matchAll(/\$\(tlt:([a-z_]+)\)/g)].map((m) => m[1])
		const defined = [...Object.keys(TALK_FLASH_VARIABLES)]
		for (const name of used) expect(defined).toContain(name)
		expect(built.triggers.talkFlashStart.events[0].options).toEqual({ variableId: 'tlt:talk_active' })
		expect(built.triggers.talkFlashStart.actions[0].options.page).toEqual({
			value: '$(tlt:talk_page)',
			isExpression: true,
		})
	})

	it('ships its Talk Light connection with the decided defaults', () => {
		expect(built.instances[CONNECTION_ID].config).toMatchObject({ app: 'tlt', talkFlashHz: 2, talkFlashCooldownS: 10 })
	})
})
